buildbot: disable pids cgroup
After updating to Podman from 4.3.x to 5.8.x, the first build container
within a worker container would always error due to pids cgroup setup:

    Error: OCI runtime error: crun: controller `pids` is not available under /sys/fs/cgroup/libpod_parent/libpod-e8d03f2ece287a916c560f6c027dce6f0edb79e4856adf956d0fdab42c79ed6a/cgroup.controllers

The second build container and any further builds would work fine.

We disable pids cgroup to make it work. We can now remove --privileged
on the worker containers in bbb-configs.