owm2meshviewer: fix missing olsr config
fix error
roles/ff_util/files/owm2meshviewer.py", line 365, in process_node_json
    node_addresses.append(owmnode["olsr"]["ipv4Config"]["config"]["mainIp"])
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'